export default {
  // ai: 'ai',
  // aiPlatform: 'ai-platform',
  // ml: 'ml',
  // mlEngine: 'ml-engine',
  // notebooks: 'notebooks',
  // apiGateway: 'api-gateway',
  // apigee: 'apigee',
  // endpoints: 'endpoints',
  // recommender: 'recommender',
  // services: 'services',
  // anthos: 'anthos',
  // billing: 'billing',
  // artifacts: 'artifacts',
  // builds: 'builds',
  // scheduler: 'scheduler',
  // tasks: 'tasks',
  // app: 'app',
  // bms: 'bms',
  // compute: 'compute',
  // container: 'container',
  // functions: 'functions',
  // run: 'run',
  // composer: 'composer',
  // dataCatalog: 'data-catalog',
  // dataflow: 'dataflow',
  // dataproc: 'dataproc',
  // metastore: 'metastore',
  // pubsub: 'pubsub',
  // bigtable: 'bigtable',
  // databaseMigration: 'database-migration',
  // datastore: 'datastore',
  // firestore: 'firestore',
  firewall: 'firewall',
  // spanner: 'spanner',
  // sql: 'sql',
  // activeDirectory: 'active-directory',
  // identity: 'identity',                
  // accessApproval: 'access-approval',
  // accessContextManager: 'access-context-manager',
  // auth: 'auth',
  folder: 'folder',
  iamPolicy: 'iamPolicy',
  // iap: 'iap',
  kms: 'kms',
  // orgPolicies: 'org-policies',
  // policyIntelligence: 'policy-intelligence',
  // policyTroubleshoot: 'policy-troubleshoot',
  // privateca: 'privateca',
  // recaptcha: 'recaptcha',
  // resourceManager: 'resource-manager',
  // resourceSettings: 'resource-settings',
  secretManager: 'secretManager',
  // iot: 'iot',
  // cloudShell: 'cloud-shell',
  // debug: 'debug',
  // deploymentManager: 'deployment-manager',
  // essentialContacts: 'essential-contacts',
  logBucket: 'logBucket',
  logSink: 'logSink',
  logView: 'logView',
  organization: 'organization',
  network: 'network',
  // organizations: 'organizations',
  project: 'project',
  storageBucket: 'storageBucket',
  subnet: 'subnet',
  // firebase: 'firebase',
  // monitoring: 'monitoring',
  // dns: 'dns',
  // domains: 'domains',
  // ids: 'ids',
  // serviceDirectory: 'service-directory',
  // workspaceAddOns: 'workspace-add-ons',
  vpc: 'vpc',
}
