export default {
  alertPolicy: 'alertPolicy',
  apiKey: 'apiKeys',
  assets: 'assets',
  // ai: 'ai',
  // aiPlatform: 'ai-platform',
  // ml: 'ml',
  // mlEngine: 'ml-engine',
  // notebooks: 'notebooks',
  // apiGateway: 'api-gateway',
  // apigee: 'apigee',
  // endpoints: 'endpoints',
  // recommender: 'recommender',
  // services: 'services',
  // anthos: 'anthos',
  // billing: 'billing',
  // artifacts: 'artifacts',
  // builds: 'builds',
  // scheduler: 'scheduler',
  // tasks: 'tasks',
  // app: 'app',
  // bms: 'bms',
  // compute: 'compute',
  // container: 'container',
  cloudFunction: 'cloudFunction',
  computeProject: 'computeProject',
  // run: 'run',
  // composer: 'composer',
  // dataCatalog: 'data-catalog',
  // dataflow: 'dataflow',
  dataprocCluster: 'dataprocClusters',
  dataprocAutoscalingPolicy: 'dataprocAutoscalingPolicies',
  dataprocJob: 'dataprocJobs',
  // metastore: 'metastore',
  // pubsub: 'pubsub',
  // bigtable: 'bigtable',
  bigQueryDataset: 'bigQueryDataset',
  bigQueryConnection: 'bigQueryConnection',
  bigQueryReservation: 'bigQueryReservation',
  bigQueryReservationCapacityCommitment: 'bigQueryReservationCapacityCommitment',
  bigQueryDataTransfer: 'bigQueryDataTransfer',
  bigQueryDataTransferRun: 'bigQueryDataTransferRun',
  // databaseMigration: 'database-migration',
  // datastore: 'datastore',
  // firestore: 'firestore',
  cloudRouter: 'cloudRouters',
  firewall: 'firewall',
  // spanner: 'spanner',
  // activeDirectory: 'active-directory',
  // identity: 'identity',
  // accessApproval: 'access-approval',
  // accessContextManager: 'access-context-manager',
  // auth: 'auth',
  folder: 'folder',
  iamPolicy: 'iamPolicy',
  // iap: 'iap',
  kmsKeyRing: 'kmsKeyRing',
  kmsCryptoKeys: 'kmsCryptoKeys',
  // orgPolicies: 'org-policies',
  // policyIntelligence: 'policy-intelligence',
  // policyTroubleshoot: 'policy-troubleshoot',
  // privateca: 'privateca',
  // recaptcha: 'recaptcha',
  // resourceManager: 'resource-manager',
  // resourceSettings: 'resource-settings',
  secretManager: 'secretManager',
  // iot: 'iot',
  // cloudShell: 'cloud-shell',
  // debug: 'debug',
  // deploymentManager: 'deployment-manager',
  // essentialContacts: 'essential-contacts',
  logBucket: 'logBucket',
  logMetric: 'logMetric',
  logSink: 'logSink',
  logView: 'logView',
  organization: 'organization',
  network: 'network',
  // organizations: 'organizations',
  project: 'project',
  sqlInstances: 'sqlInstances',
  sslPolicies: 'sslPolicies',
  serviceAccount: 'serviceAccounts',
  storageBucket: 'storageBucket',
  subnet: 'subnet',
  targetSslProxies: 'targetSslProxies',
  targetHttpsProxies: 'targetHttpsProxies',
  // firebase: 'firebase',
  // monitoring: 'monitoring',
  dnsManagedZone: 'dnsManagedZone',
  dnsPolicy: 'dnsPolicy',
  // dns: 'dns',
  // domains: 'domains',
  // ids: 'ids',
  // serviceDirectory: 'service-directory',
  // workspaceAddOns: 'workspace-add-ons',
  vmInstance: 'vmInstance',
  vpcConnector: 'vpcConnectors',
}
